both packages fail with same file (file was migrated likely)
Filtering out excluded symbols and summarizing items...
ERROR: The command 'cvs -Q -R -f -d :local:/home/users/glen/git/pld-git co -r1.17 -p -kk packages/vim-syntax-spec/spec.vim' failed with exit status=0
and the following output:
cvs checkout: Skipping `$Log$' keyword due to excessive comment leader.